#### general settings
name: HGT
train_type: gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset_path: "./data/mimic3_objects/mimic3_dp.pkl"
  graph_path: "./data/graphs/mimic3_dp.pkl"
  labels_path: "./data/graphs/mimic3_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic3_dp_entity_mapping.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HGT_MIMIC3_Readm"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001 # Learning rate
  weight_decay: 0.001

#### GNN settings
GNN:
  name: "HGT"
  num_layers: 2
  in_dim: 128
  hidden_dim: 256
  out_dim: 2
  num_heads: 4
  num_out_heads: 1
  feat_drop: 0.1

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 200
  batch_size: 4096
