raw: "physionet.org/mimiciii/"
dataset_name: "mimic3_dp"  # d: +diagnosis table; p: + procedure table
processed_path: "./data/mimic3_objects/"
graph_output_path: "./data/graphs/"

all_stays_path: "./data/root/all_stays.csv"
all_diagnoses_path: "./data/root/all_diagnoses.csv"
